{
  "_annotation": {
    "cve_id": "CVE-2024-21502",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "snapshot": "https://raw.githubusercontent.com/anchore/nvd-data-overrides/main/.snapshot/2024/CVE-2024-21502.json",
    "triage_notes": {
      "references": [
        "https://github.com/AntonKueltz/fastecdsa/commit/57fc5689c95d649dab7ef60cc99ac64589f01e36",
        "https://security.snyk.io/vuln/SNYK-PYTHON-FASTECDSA-6262045",
        "https://gist.github.com/keltecc/49da037072276f21b005a8337c15db26",
        "https://github.com/AntonKueltz/fastecdsa/blob/v2.3.1/src/curveMath.c%23L210"
      ]
    }
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:fastecdsa_project:fastecdsa:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "B354D93C-7344-50BE-A3CF-923E213C482B",
                "versionEndExcluding": "2.3.2",
                "versionStartIncluding": "0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}