{
  "_annotation": {
    "cve_id": "CVE-2024-29033",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "snapshot": "https://raw.githubusercontent.com/anchore/nvd-data-overrides/main/.snapshot/2024/CVE-2024-29033.json",
    "triage_notes": {
      "references": [
        "https://github.com/jupyterhub/oauthenticator/commit/5246b09675501b09fb6ed64022099b7644812f60",
        "https://trufflesecurity.com/blog/google-oauth-is-broken-sort-of",
        "https://github.com/jupyterhub/oauthenticator/security/advisories/GHSA-55m3-44xf-hg4h"
      ]
    }
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:jupyter:oauthenticator:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "1C34D747-CAC6-501A-AC8F-832B4B7648CF",
                "versionEndExcluding": "16.3.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}